language: node_js
node_js:
  - "lts/*"

sudo: required

services:
  - docker

cache:
  directories:
    - code/game-library-proto/mariadb/data/test
    - code/game-library-proto/node_modules

install:
  - cd code/game-library-proto
  - npm run docker-test
  - npm install
  - cp config/default.json.template config/default.json

before_script:
  - sleep 15

script:
  - npm test
