language: node_js
node_js:
  - "lts/*"

sudo: required

services:
  - docker

cache:
  directories:
    - game-library/node_modules

install:
  - cd game-library/
  - npm run docker-test-travis
  - npm install
  - cp config/default.json.template config/default.json

before_script:
  - sleep 15

script:
  - npm test
