# docker-compose.yml
# local mariaDB service
# from https://hub.docker.com/_/mariadb/

# start with "docker-compose up -d" from the same folder as this file
# stop with "docker-compose down" from the same folder as this file

# creates a local folder "./db-data/" to hold the db and related files

# Use root/password as user/password credentials
# for logging into the database at localhost:3306

# adminer is a db admin frontend that you can use
# at http://localhost:8080/

version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
