# sample docker-compose.yml
# from https://hub.docker.com/_/mariadb/

# Use root/password as user/password credentials
# adminer is a db admin frontend, but
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
